apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-grafana
  namespace: obcluster
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
