apiVersion: cloud.oceanbase.com/v1
kind: Backup
metadata:
  name: ob-backup
  namespace: obcluster
spec:
  destPath: /ob-backup
  source:
    clusterName: ob-test
    clusterID: 1
    clusterNamespace: obcluster
  schedule:
  - name: full
    schedule: once
  - name: incremental 
    schedule: once
  parameters: 
