apiVersion: cloud.oceanbase.com/v1		
kind: Tenant		
metadata:		
  name: tenant1		
  namespace: obcluster		
spec:	
  # 必填
  clusterName: ob-test		
  clusterID: 1		# 主备库
  # 非必填
  charset:  # 租户的字符集
  collate:  # 租户校对规则
  mode: 
  logonlyReplicaNum:

  variables: 
    - name: ob_tcp_invited_nodes
      value: '%'

  topology:
    - zone: zone1
      unitNum: 3 # 指定要创建的单个 ZONE 下的单元个数，取值要小于单个 ZONE 中的 OBServer 个数。
      type: 
        name: FUll # FULL READONLY LOGONLY , 需要写出完整类型, 大小写不敏感
        replica: 1 # FULL 和 LOGONLY 类型只能设置1
      priority: 3 # 可选，表示当前zone的优先级，数字越大优先级越高，没有填写的放在最后面
      resource:
        maxCPU: 2500m # 租户可用最大 CPU 数。可以使用int，float类型需要写成 ***m
        minCPU: 2 # 租户可用最小 CPU 数。
        maxMemory: 1Gi # 租户可用最大内存。string 类型，需要写单位
        minMemory: 1Gi # 租户可用最小内存。string 类型，需要写单位
        # 非必填
        maxDiskSize: 1Gi # 租户可用最大磁盘空间。string 类型，需要写单位。不填默认 512Mi
        maxSessionNum: 64 # 租户最大 SESSION 数，取值范围为 [64,+∞)。不填默认 64
        maxIops: 256 # 租户 IOPS 最多数量，取值范围为 [128,+∞)。不填默认 128
        minIops: 256 # 租户 IOPS 最少数量。取值范围为 [128,+∞)。不填默认128
    - zone: zone2
      unitNum: 1
      type: 
        name: Full
        replica: 1
      resource:
        maxCPU: 2500m 
        minCPU: 2 
        maxMemory: 1Gi 
        minMemory: 1Gi 
        # 非必填
        maxDiskSize: 1Gi
        maxSessionNum: 64 
        maxIops: 256
        minIops: 256
    # - zone: zone3
    #   unitNum: 2
    #   type: 
    #     name: Full
    #     replica: 1
    #   priority: 3
    #   resource:
    #     maxCPU: 2500m 
    #     minCPU: 2 
    #     maxMemory: 1Gi 
    #     minMemory: 1Gi 
    #     # 非必填
    #     maxDiskSize: 1Gi
    #     maxSessionNum: 64 
    #     maxIops: 256
    #     minIops: 256